% Advanced Deep Learning Framework AquaSense for Comprehensive Marine Pollutant Detection Using Sentinel-2 Multispectral Data
clear; close all; clc;
disp("|-----------------------------------------------------------------------------------------------------------------------------|");
disp(" Advanced Deep Learning Framework AquaSense for Comprehensive Marine Pollutant Detection Using Sentinel-2 Multispectral Data ");
disp("|-----------------------------------------------------------------------------------------------------------------------------|");
pause(5);
disp("|-------------------------------------------|");
disp(" Marine Debris and Oil Spill Dataset (MADOS)");
disp("|-------------------------------------------|");
fprintf('\n');
pause(5);
disp("|---------------------|");
disp(" Data Preprocessing ");
disp("|---------------------|");
fprintf('\n');
pause(5);
Data_Preprocessing()
uiwait(msgbox(' Data_Preprocessing is Successfully Completed...','Message Box','modal'));
pause(5);
disp("|------------------|");
disp(" Annotate Data ");
disp("|------------------|");
fprintf('\n');
pause(5);
Annotate_Data();
uiwait(msgbox(' Annotate_Data is Successfully Completed...','Message Box','modal'));
pause(5);
disp("|---------------|");
disp(" Segmentation ");
disp("|---------------|");
fprintf('\n');
pause(5);
Segmentation();
uiwait(msgbox(' Segmentation is Successfully Completed...','Message Box','modal'));
pause(5);
disp("|-----------------------------------------|");
disp(" Framework Design - AquaSense Framework ");
disp("|-----------------------------------------|");
fprintf('\n');
pause(5);
Classification();
uiwait(msgbox(' Classification process is Successfully Completed...','Message Box','modal'));
disp("|----------------------|");
disp(" Performance Metrics ");
disp("|----------------------|");
fprintf('\n');
pause(5);
Performance_Metrics();
disp("|----------|");
disp(" END ");
disp("|----------|");

